[build]
  base = ""
  publish = "Frontend"
  functions = "netlify/functions"

# Allow assets during maintenance
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = false

# Serve maintenance page during maintenance
[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true
  conditions = {Language = ["en"]}

# Redirect back to the main site after maintenance
[[redirects]]
  from = "/maintenance.html"
  to = "/"
  status = 302
  force = true
  conditions = {Cookie = ["maintenance=false"]} # Use cookie to control redirection
