[build]
  base = ""
  publish = "Frontend"
  functions = "netlify/functions"



[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true