[build]
  functions = "netlify/functions"
  publish = "Frontend"  # Adjust if your files are in a different directory

[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true
