[build]
  base = "BALAJI ELECTRICALS"
  publish = "BALAJI ELECTRICALS/Frontend"
  functions = "BALAJI ELECTRICALS/netlify/functions"


[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true
