[build]
  functions = "netlify/functions"
  publish = "Frontend"  # Correct this path

[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true