[build]
  base = ""
  publish = "Frontend"
  functions = "netlify/functions"

# Allow images and assets to load during maintenance
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = false

# Catch-all for maintenance (everything except images)
[[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 503
  force = true
  conditions = {Language = ["en"]}

# Bypass for favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = false
