[build]
  base = ""
  publish = "Frontend"
  functions = "netlify/functions"

# Allow assets during maintenance
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = false

# Serve maintenance page during maintenance
#[[redirects]]
#  from = "/*"
#  to = "/maintenance.html"
#  status = 503
#  force = true
#  conditions = {Language = ["en"]}

